# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23eb8ac20615278bb5aef9f184b672e13c4786ddfd112855d2d9daec01261b4e58db71ab05ef815c4673a3c3115f8588e7809ed70447e1a212a899c31653175a

test:
  secret_key_base: b85ec1c1c14e86d09389d8f1ed89ac9e42c1a1d7feae9a19646be9294c52ecafbc1ed0f3afe88041f20b0c9e60d8f9a95cf4d4e7ff7b98e10614e08b8b41978b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
